name: UiPath Automation Pipeline
env:
  TEST_SETS: "HelloWorld_TestSet"
  #DOCKER_TLS_CERTDIR: ""
  #DOCKER_HOST: tcp://docker:2375
on:
  push:
    branches:
      - main
jobs:
  robot_installation:
    name: Robot Installation
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7-dind
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Check Docker
        run: docker info
      - name: Pull and Run UiPath Robot Container
        run: |
          if docker ps -a --format '{{.Image}}' | grep -q "uiautomation-runtime:latest24.10"; then
            echo "Robot already installed. Skipping pull and run steps."
          else
            docker pull registry.uipath.com/robot/runtime
            docker run -e LICENSE_AGREEMENT=accept -e ORCHESTRATOR_URL="https://cloud.uipath.com/praveenakolluri/DefaultTenant/orchestrator_/" -e MACHINE_KEY="ee49af86-d1cd-4459-b4eb-7ea55b994c77" -tid registry.uipath.com/robot/uiautomation-runtime:latest24.10
          fi
      - name: Run Test with UiPath CLI
        run: |
          cd ./uipathcli/tools
          chmod 777 uipcli.dll
          dotnet uipcli.dll test run "https://cloud.uipath.com/" DefaultTenant -A praveenakolluri -I 18dfa18c-d561-404a-8963-73c2018a246e -S "XA)0HjXiHe7SB9LT" --applicationScope "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Robots.Read OR.Settings.Read OR.Tasks OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users.Read" -s "CrossPlatform" -o "Shared"
